name: Frontend CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./GoodFood-FE #default working directory

    steps:
      #1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      #2. Setup node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      
      #3. Install dependencies
      - name: Install dependencies
        run: npm ci

      #4. Lint code (so many things to lint => disabled for now)
      # - name: Lint code
      #   run: npm run lint

      #5. Run tests
      - name: Run tests
        run: npm test
      
      #6. Build project
      - name: Build project
        run: npm run build

      #7. Build docker image to validate Dockerfile
      - name: Build Docker image
        run: docker build -t goodfood-frontend

      #8. Optional: Push Docker image to registry
      #- name: Login to Docker Hub
      #  run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      #- name: Push image
      #  run: docker push goodfood-frontend